// Date: 13/07/2014 09:04:07
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package steamcraft.client.renderers.tile;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.tileentity.TileEntity;
import steamcraft.common.items.BaseElectricItem;
import steamcraft.common.tiles.TileBattery;

public class ModelBattery extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer upright;
    ModelRenderer top;
    ModelRenderer jar;
    ModelRenderer lid;
    ModelRenderer wire;
    ModelRenderer jar2;
    ModelRenderer lid2;
    ModelRenderer wire2;
    ModelRenderer jar3;
    ModelRenderer lid3;
    ModelRenderer wire3;
    ModelRenderer jar4;
    ModelRenderer lid4;
    ModelRenderer wire4;

  public ModelBattery()
  {
	  textureWidth = 64;
	  textureHeight = 32;

      base = new ModelRenderer(this, 0, 0);
      base.addBox(0F, 0F, 0F, 2, 1, 16);
      base.setRotationPoint(0F, 0F, 0F);
      base.setTextureSize(64, 32);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      upright = new ModelRenderer(this, 0, 0);
      upright.addBox(0F, 0F, 0F, 2, 5, 2);
      upright.setRotationPoint(0F, -5F, 7F);
      upright.setTextureSize(64, 32);
      upright.mirror = true;
      setRotation(upright, 0F, 0F, 0F);
      top = new ModelRenderer(this, 0, 0);
      top.addBox(0F, 0F, 0F, 4, 1, 14);
      top.setRotationPoint(-1F, -6F, 1F);
      top.setTextureSize(64, 32);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      jar = new ModelRenderer(this, 0, 0);
      jar.addBox(0F, 0F, 0F, 3, 4, 3);
      jar.setRotationPoint(-3F, -3F, 2F);
      jar.setTextureSize(64, 32);
      jar.mirror = true;
      setRotation(jar, 0F, 0F, 0F);
      lid = new ModelRenderer(this, 0, 0);
      lid.addBox(0F, 0F, 0F, 2, 1, 2);
      lid.setRotationPoint(-2.5F, -4F, 2.5F);
      lid.setTextureSize(64, 32);
      lid.mirror = true;
      setRotation(lid, 0F, 0F, 0F);
      wire = new ModelRenderer(this, 0, 0);
      wire.addBox(0F, 0F, 0F, 2, 1, 1);
      wire.setRotationPoint(-1.8F, -5F, 3F);
      wire.setTextureSize(64, 32);
      wire.mirror = true;
      setRotation(wire, 0F, 0F, 0F);
      jar2 = new ModelRenderer(this, 0, 0);
      jar2.addBox(0F, 0F, 0F, 3, 4, 3);
      jar2.setRotationPoint(-3F, -3F, 6.5F);
      jar2.setTextureSize(64, 32);
      jar2.mirror = true;
      setRotation(jar2, 0F, 0F, 0F);
      lid2 = new ModelRenderer(this, 0, 0);
      lid2.addBox(0F, 0F, 0F, 2, 1, 2);
      lid2.setRotationPoint(-2.5F, -4F, 7F);
      lid2.setTextureSize(64, 32);
      lid2.mirror = true;
      setRotation(lid2, 0F, 0F, 0F);
      wire2 = new ModelRenderer(this, 0, 0);
      wire2.addBox(0F, 0F, 0F, 2, 1, 1);
      wire2.setRotationPoint(-2F, -5F, 7.5F);
      wire2.setTextureSize(64, 32);
      wire2.mirror = true;
      setRotation(wire2, 0F, 0F, 0F);
      jar3 = new ModelRenderer(this, 0, 0);
      jar3.addBox(0F, 0F, 0F, 3, 4, 3);
      jar3.setRotationPoint(-3F, -3F, 11F);
      jar3.setTextureSize(64, 32);
      jar3.mirror = true;
      setRotation(jar3, 0F, 0F, 0F);
      lid3 = new ModelRenderer(this, 0, 0);
      lid3.addBox(0F, 0F, 0F, 2, 1, 2);
      lid3.setRotationPoint(-2.5F, -4F, 11.5F);
      lid3.setTextureSize(64, 32);
      lid3.mirror = true;
      setRotation(lid3, 0F, 0F, 0F);
      wire3 = new ModelRenderer(this, 0, 0);
      wire3.addBox(0F, 0F, 0F, 2, 1, 1);
      wire3.setRotationPoint(-1.5F, -5F, 12F);
      wire3.setTextureSize(64, 32);
      wire3.mirror = true;
      setRotation(wire3, 0F, 0F, 0F);
      jar4 = new ModelRenderer(this, 0, 0);
      jar4.addBox(0F, 0F, 0F, 3, 4, 3);
      jar4.setRotationPoint(2F, -3F, 2F);
      jar4.setTextureSize(64, 32);
      jar4.mirror = true;
      setRotation(jar4, 0F, 0F, 0F);
      lid4 = new ModelRenderer(this, 0, 0);
      lid4.addBox(0F, 0F, 0F, 2, 1, 2);
      lid4.setRotationPoint(2.5F, -4F, 2.5F);
      lid4.setTextureSize(64, 32);
      lid4.mirror = true;
      setRotation(lid4, 0F, 0F, 0F);
      wire4 = new ModelRenderer(this, 0, 0);
      wire4.addBox(0F, 0F, 0F, 2, 1, 1);
      wire4.setRotationPoint(2F, -5F, 3F);
      wire4.setTextureSize(64, 32);
      wire4.mirror = true;
      setRotation(wire4, 0F, 0F, 0F);
  }

  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, TileEntity tile)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    base.render(f5);
    upright.render(f5);
    top.render(f5);
    if(tile != null)
    {
        TileBattery te = (TileBattery)tile;
        ModelRenderer[] jars = { this.jar, this.jar2, this.jar3, this.jar4 };
        ModelRenderer[] lids = { this.lid, this.lid2, this.lid3, this.lid4 };
        ModelRenderer[] wires = { this.wire, this.wire2, this.wire3, this.wire4 };
          for (int i = 0; i < jars.length; i++)
          {
        	  if(te.inventory[i] != null)
        	  {
        		  jars[i].render(f5);
        		  lids[i].render(f5);
        		  wires[i].render(f5);
        	  }
          }
    }
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
